# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - help wanted
  - good first issue
  - enhancement
  - in progress
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: "이 이슈는 최근 활동이 없어 자동으로 스테일(stale)로 표시되었습니다. 추가 활동이 없으면 종료됩니다. 기여해 주셔서 감사합니다."
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true